name = "blogbote"
main = "./dist/_worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

# Workers 静态资源托管配置
[assets]
directory = "./dist"
binding = "ASSETS"
html_handling = "auto-trailing-slash"
not_found_handling = "404-page"

# Workers AI 绑定
[ai]
binding = "AI"

# KV 命名空间绑定
[[kv_namespaces]]
binding = "SESSION"
id = "d4f8ebf92e1246aa9a0ffb687fce6b63"

# 环境变量
[vars]
CHANNEL = "siweishiya"
LOCALE = "zh-cn"
TIMEZONE = "Asia/Shanghai"
COMMENTS = "true"
REACTIONS = "true"
RSS_BEAUTIFY = "true"
