name = "siweishiya-blog"
main = "./dist/_worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

# Workers 静态资源托管
[assets]
directory = "./dist"
binding = "ASSETS"
html_handling = "auto-trailing-slash"
not_found_handling = "404-page"

# 环境变量
[vars]
CHANNEL = "siweishiya"
LOCALE = "zh-cn"
TIMEZONE = "Asia/Shanghai"
COMMENTS = "true"
REACTIONS = "true"
RSS_BEAUTIFY = "true"

